# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package definitions and TypeScript config
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies without running any prepare scripts
RUN npm install --ignore-scripts

# Copy source code and build
COPY src ./src
RUN npm run build

# Default command to start the MCP server over stdio
CMD ["node", "dist/index.js"]
