# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js LTS Alpine as build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci && npm run build

# --- Runtime stage ---
FROM node:lts-alpine
WORKDIR /app

# Copy only production dependencies and built files
COPY package.json package-lock.json ./
RUN npm ci --production
COPY --from=builder /app/dist ./dist

# Expose optional port if any (stdio server doesn't use HTTP port)
# Start the MCP stdio server
CMD ["node", "dist/index.js"]
